@startuml

    |Менеджер|

        start;

        #bbdaff:Натискає на кнопку відображення
        співавторів набору;

    |Система|

        #f0f0f0:Отримує інформацію з бази даних
        про співавторів обраного набору;

        #f0f0f0:Відображає список співавторів обраного набору
        з ім'ям акаунта та сферою зайнятості кожного;
        
    |Менеджер|

        #bbdaff:Натискає на кнопку видалення
        на бажаному співавторі;

    |Система|

        #f0f0f0:Надає поле для введення
        паролю для підтвердження дії;

    |Менеджер|

        #bbdaff:Уводить пароль у надане поле;

    |Система|

        #f0f0f0:Перевіряє введений пароль
        на правильність;

        note right #f77
            Можлива <b><i>EX.m.cd.2</i></b>
        end note

        #f0f0f0:Видаляє вказаного співавтора зі спавівторів
        обраного набору в базі даних;

        #f0f0f0:Отримує з бази даних електронну
        адресу вказаного співавтора;

        #f0f0f0:Повідомляє менеджера про
        видаленого співавтора;

        #f0f0f0:Сповіщає видаленого співавтора про позбавлення
        прав щодо обраного набору електронним листом;

    |Менеджер|

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml