@startuml

    |Менеджер|

        start;

        #bbdaff:Натискає на кнопку відображення
        своїх наборів даних;

    |Система|

        #f0f0f0:Отримує інформацію з бази даних
        про набори даних менеджера;

        #f0f0f0:Відображає список наборів даних менеджера
        із загальною інформацією про кожний:
        назвою, датою останньої зміни, описом;
        
    |Менеджер|

        #bbdaff:Натискає на бажаний набір;

    |Система|

        #f0f0f0:Відображає сторінку з назвою, <i>Concepts</i>,
        <i>Entities</i>, <i>Datapoints</i>, <i>Metadata</i>,
        <i>Synonyms</i> обраного набору;

    |Менеджер|

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml