@startuml

    |Менеджер|

        start;

        #bbdaff:Натискає на кнопку додання співавтора;

    |Система|

        #f0f0f0:Надає поле для введення
        паролю для підтвердження дії;

    |Менеджер|

        #bbdaff:Уводить пароль у надане поле;

    |Система|

        #f0f0f0:Перевіряє введений пароль
        на правильність;

        note right #f77
            Можлива <b><i>EX.m.cd.1.1</i></b>
        end note

        #f0f0f0:Надає поле для введення імені акаунта
        майбутнього менеджера-співавтора;
        
    |Менеджер|

        #bbdaff:Уводить ім'я акаунта майбутнього
        менеджера-співавтора;

    |Система|

        #f0f0f0:Отримує інформацію про електронну
        адресу акаунта з бази даних за
        введеним ім'ям;

        note right #f77
            Можлива <b><i>EX.m.cd.1.2</i></b>
        end note

        #f0f0f0:Вносить у базу даних інформацію про вказаного
        нового співавтора обраного набору;

        #f0f0f0:Повідомляє менеджера про доданого співавтора;

        #f0f0f0:Сповіщає доданого співавтора про надані права
        щодо обраного набору електронним листом;

    |Менеджер|

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml