@startuml

    |Менеджер|

        start;

        #bbdaff:Натискає на кнопку входу в акаунт;

    |Система|

        #f0f0f0:Надає автентифікаційну форму;
        
    |Менеджер|

        #bbdaff:Заповнює автентифікаційну форму
        (ім'я акаунта, пароль) і надсилає її;

    |Система|

        #f0f0f0:Здійснює пошук уведеної
        комбінації в базі даних;

        note right #f77
            Можлива <b><i>EX.m.0</i></b>
        end note

        #f0f0f0:Авторизує менеджера;

        #f0f0f0:Відображає домашню сторінку
        акаунта менеджера;

    |Менеджер|
    
        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml