@startuml

    |Менеджер|

        start;

        #bbdaff:Натискає на кнопку створення нового набору даних;

    |Система|

        #f0f0f0:Надає форму для вказання назви набору й назв
        використовуваних колекцій (<i>Concepts</i>, <i>Entities</i>, <i>Datapoints</i>);

    |Менеджер|

        #bbdaff:Заповнює надану форму;

        #bbdaff:Натискає на кнопку відображення
        наступної сторінки створення набору;

    |Система|

        #f0f0f0:Зберігає введені дані про назву набору та використовувані
        колекції <i>Concepts</i>, <i>Entities</i>, <i>Datapoints</i>;

        #f0f0f0:Надає форму для введення <i>Synonyms</i> та <i>Metadata</i>;

    |Менеджер|

        #bbdaff:Заповнює надану форму;

        #bbdaff:Натискає на кнопку перегляду всіх уведених
        даних, з яких буде створено набір даних;

    |Система|

        #f0f0f0:Зберігає введені дані про <i>Synonyms</i> та <i>Metadata</i>;

        #f0f0f0:Перевіряє, чи всі вказані
        колекції існують;

        note right #f77
            Можлива <b><i>EX.m.4</i></b>
        end note

        #f0f0f0:Відображає всі дані, введені менеджером;

    |Менеджер|

        #bbdaff:Натискає на кнопку створення набору;

    |Система|

        #f0f0f0:Створює набір даних зі всіх уведених даних;

        #f0f0f0:Вносить інформацію про новий набір у базу даних;

        #f0f0f0:Повідомляє менеджера про створення нового набору;

    |Менеджер|

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml