@startuml

    |Менеджер|

        start;

        #bbdaff:Менеджер натискає на кнопку
        видалення набору даних;

    |Система|

        #f0f0f0:Надає поле для введення
        паролю для підтвердження дії;

    |Менеджер|

        #bbdaff:Уводить пароль у надане поле;

    |Система|

        #f0f0f0:Перевіряє введений пароль
        на правильність;

        note right #f77
            Можлива <b><i>EX.m.cd.3</i></b>
        end note

    |Система|

        #f0f0f0:Видаляє набір даних з бази даних;

        #f0f0f0:Повідомляє менеджера про
        видалення набору;

    |Менеджер|

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml