@startuml

    |Користувач|

        start;

        #fff8bd:Натискає на кнопку реєстрації;

    |Система|

        #f0f0f0:Надає реєстраційну форму;
        
    |Користувач|

        #fff8bd:Заповнює реєстраційну форму: ім'я акаунта,
        сфера зайнятості, електронна адреса, пароль;

        #fff8bd:Натискає на кнопку надіслання
        реєстраційної форми;

    |Система|

        #f0f0f0:Вносить дані про новий акаунт в базу даних;

        #f0f0f0:Повідомляє менеджера про створений акаунт;

    |Користувач|

        stop;

    right footer
        <b>Bricks</b>
        НТУУ "КПІ"
        Київ — 2020
    end footer

@enduml